services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calkit_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build: ./backend
    command: sh -c "npm install && node api/index.js"
    environment:
      PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: app_db
      JWT_SECRET: dev_jwt_secret
      GMAIL_USER: ""
      GMAIL_APP_PASSWORD: ""
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
volumes:
  db_data:
